name: Renv use directory flow
on:
  push:


jobs:
  ci-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install renv
        uses: r-lib/actions/setup-renv@v2

      - name: Check status
        run: |
          make check_R
      
      - name: Lint
        run: |
          make lint
      
      - name: Test
        run: |
          make test

  build-app:
    needs: ci-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yashikab/r-sample:latest
          target: production
          cache-from: type=registry,ref=yashikab/r-sample:buildcache
          cache-to: type=registry,ref=yashikab/r-sample:buildcache,mode=max
