name: R sample flow
on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yashikab/r-sample-ci:latest
          target: ci
          cache-from: type=registry,ref=yashikab/r-sample-ci:buildcache
          cache-to: type=registry,ref=yashikab/r-sample-ci:buildcache,mode=max
      - name: check volume
        run: echo ${{ github.workspace }}
  ci-check:
    needs: docker-build
    runs-on: ubuntu-latest
    container:
      image: yashikab/r-sample-ci:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    defaults:
      run:
        working-directory: /ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy sources
        run: cp -r ${GITHUB_WORKSPACE}/src /ci/src
      - name: Check R status
        run: make check_R
      - name: Lint
        run: make lint
      - name: Test
        run: make test
